import localFont from "next/font/local";
import {Raleway} from 'next/font/google'
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from '@/components/Header'

const raleway = Raleway({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Uber Clone",
  description: "Uber Clone App Generated By @joysarkar077",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={raleway.className}>
        <Header/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
